AllCops:
  Exclude:
    - "**/vendor/**/*"
    - "**/*.gemspec"
    - "spec/**"
  NewCops: enable
  TargetRubyVersion: 3.2.2
  SuggestExtensions: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes